name: Run Unittests
on: [push, pull_request]

jobs:
  dubtest:
    name: Dub Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v1
        with:
          compiler: ldc-latest

      - uses: WebFreak001/dub-upgrade@v0.0.10

      - name: Run tests
        run: dub test

      - uses: WebFreak001/dub-upgrade@v0.0.10
        with:
          store: true # cache binaries
