name: Run Unittests
on: [push, pull_request]

jobs:
  dubtest:
    name: Dub Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v1
        with:
          compiler: ldc-latest

      - name: dub upgrade
        run: dub upgrade

      - name: Run tests
        run: dub test
